# Copyright 2025 Antonio Ojea
# SPDX-License-Identifier: Apache-2.0
version: 2

run:
  timeout: 30m
  tests: false # TODO lint tests too

linters:
  default: none
  enable:
    - gocritic
    - govet
    - errcheck
    - ineffassign
    - staticcheck

formatters:
  enable:
    - goimports
    - gofmt